"""The persistence boundary of the whole job aggregate. Resume is built on this."""

from pathlib import Path
from typing import Protocol

from transcribe.domain.chunking import ChunkPlan, ChunkResult
from transcribe.domain.generation import GenerationResult
from transcribe.domain.ids import JobId
from transcribe.domain.jobs import JobRecord
from transcribe.domain.transcript import Transcript


class TranscriptStoragePort(Protocol):
    def create_job(self, job: JobRecord) -> None: ...

    def load_job(self, job_id: JobId) -> JobRecord: ...

    def update_job(self, job: JobRecord) -> None: ...

    def list_jobs(self) -> tuple[JobRecord, ...]: ...

    def save_chunk_plan(self, job_id: JobId, plan: ChunkPlan) -> None: ...

    def load_chunk_plan(self, job_id: JobId) -> ChunkPlan | None: ...

    def save_chunk_result(self, result: ChunkResult) -> None:
        """MUST be atomic."""
        ...

    def load_chunk_results(self, job_id: JobId) -> tuple[ChunkResult, ...]: ...

    def save_transcript(self, transcript: Transcript) -> None: ...

    def load_transcript(self, job_id: JobId) -> Transcript | None: ...

    def save_artifacts(self, job_id: JobId, artifacts: GenerationResult) -> None: ...

    def export_text(self, job_id: JobId, text: str) -> Path: ...
